

import ClientServer.ClientServer;

import java.awt.Color;
import javax.swing.JOptionPane;

import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author admin
 */
public class MainFrame extends javax.swing.JFrame {
    public static Socket cs=null;
    public static DataInputStream din=null;
    public static DataOutputStream dout=null;
    public static ObjectInputStream oin=null;
    public static ObjectOutputStream oout=null;
    
    public static int studentId=0;
    /**
     * Creates new form MainFrame
     * @throws java.io.IOException
     */
    public MainFrame() throws IOException {
    initComponents();
    this.setTitle("Online Aptitude Test");
    cs=new Socket("localhost", 6000);
    dout=new DataOutputStream(cs.getOutputStream());
    oout=new ObjectOutputStream(cs.getOutputStream());
    din=new DataInputStream(cs.getInputStream());
    oin=new ObjectInputStream(cs.getInputStream());
        
    }

    
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        TabPanel = new javax.swing.JPanel();
        Login = new javax.swing.JLabel();
        icon = new javax.swing.JLabel();
        TeacherLoginTab = new javax.swing.JPanel();
        teacherlogin = new javax.swing.JLabel();
        arrowicon = new javax.swing.JLabel();
        icon1 = new javax.swing.JLabel();
        StudentLoginTab = new javax.swing.JPanel();
        icon2 = new javax.swing.JLabel();
        arrowicon2 = new javax.swing.JLabel();
        studentlogin = new javax.swing.JLabel();
        LayeredPanel = new javax.swing.JLayeredPane();
        TeacherLoginPanel = new javax.swing.JPanel();
        teacherlogintitle = new javax.swing.JLabel();
        teacherid = new javax.swing.JLabel();
        teacheridtextbox = new javax.swing.JTextField();
        teacherpassword = new javax.swing.JLabel();
        teacherpasswordtextbox = new javax.swing.JPasswordField();
        TeacherLoginButton = new javax.swing.JButton();
        WrongPasswordLabel = new javax.swing.JLabel();
        StudentLoginPanel = new javax.swing.JPanel();
        StudentLoginTitle = new javax.swing.JLabel();
        StudentId = new javax.swing.JLabel();
        StudentIdTextBox = new javax.swing.JTextField();
        StudentPassword = new javax.swing.JLabel();
        StudentPasswordTextBox = new javax.swing.JPasswordField();
        StudentLoginButton = new javax.swing.JButton();
        WrongPasswordLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        MainPanel.setBackground(new java.awt.Color(255, 255, 255));

        TabPanel.setBackground(new java.awt.Color(0, 0, 51));

        Login.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        Login.setForeground(new java.awt.Color(255, 255, 255));
        Login.setText("LOGIN");

        icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/businessman-64.png"))); // NOI18N

        TeacherLoginTab.setBackground(new java.awt.Color(0, 0, 102));
        TeacherLoginTab.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        TeacherLoginTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TeacherLoginTabMousePressed(evt);
            }
        });

        teacherlogin.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        teacherlogin.setForeground(new java.awt.Color(255, 255, 255));
        teacherlogin.setText("TEACHER LOGIN");
        teacherlogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                teacherloginMousePressed(evt);
            }
        });

        arrowicon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        arrowicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arrow-24-16.png"))); // NOI18N

        icon1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/businessman-16 (1).png"))); // NOI18N

        javax.swing.GroupLayout TeacherLoginTabLayout = new javax.swing.GroupLayout(TeacherLoginTab);
        TeacherLoginTab.setLayout(TeacherLoginTabLayout);
        TeacherLoginTabLayout.setHorizontalGroup(
            TeacherLoginTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TeacherLoginTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icon1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(teacherlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(arrowicon)
                .addContainerGap())
        );
        TeacherLoginTabLayout.setVerticalGroup(
            TeacherLoginTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TeacherLoginTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TeacherLoginTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(icon1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(TeacherLoginTabLayout.createSequentialGroup()
                        .addGroup(TeacherLoginTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(teacherlogin)
                            .addComponent(arrowicon))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        StudentLoginTab.setBackground(new java.awt.Color(0, 0, 51));
        StudentLoginTab.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        StudentLoginTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                StudentLoginTabMousePressed(evt);
            }
        });

        icon2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/businessman-16 (1).png"))); // NOI18N

        arrowicon2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        arrowicon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arrow-24-16.png"))); // NOI18N

        studentlogin.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        studentlogin.setForeground(new java.awt.Color(255, 255, 255));
        studentlogin.setText("STUDENT LOGIN");
        studentlogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                studentloginMousePressed(evt);
            }
        });

        javax.swing.GroupLayout StudentLoginTabLayout = new javax.swing.GroupLayout(StudentLoginTab);
        StudentLoginTab.setLayout(StudentLoginTabLayout);
        StudentLoginTabLayout.setHorizontalGroup(
            StudentLoginTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StudentLoginTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icon2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(studentlogin, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(arrowicon2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        StudentLoginTabLayout.setVerticalGroup(
            StudentLoginTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentLoginTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(StudentLoginTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(icon2, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                    .addGroup(StudentLoginTabLayout.createSequentialGroup()
                        .addGroup(StudentLoginTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(arrowicon2)
                            .addComponent(studentlogin))
                        .addGap(0, 2, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout TabPanelLayout = new javax.swing.GroupLayout(TabPanel);
        TabPanel.setLayout(TabPanelLayout);
        TabPanelLayout.setHorizontalGroup(
            TabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TeacherLoginTab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(TabPanelLayout.createSequentialGroup()
                .addGroup(TabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TabPanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(icon, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(TabPanelLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(Login)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(TabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(StudentLoginTab, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TabPanelLayout.setVerticalGroup(
            TabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(Login)
                .addGap(18, 18, 18)
                .addComponent(icon, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(TeacherLoginTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(TabPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(TabPanelLayout.createSequentialGroup()
                    .addGap(175, 175, 175)
                    .addComponent(StudentLoginTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(248, Short.MAX_VALUE)))
        );

        TeacherLoginPanel.setBackground(new java.awt.Color(255, 255, 255));

        teacherlogintitle.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        teacherlogintitle.setText("TEACHER LOGIN");

        teacherid.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        teacherid.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        teacherid.setText("Teacher ID:");

        teacheridtextbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacheridtextboxActionPerformed(evt);
            }
        });

        teacherpassword.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        teacherpassword.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        teacherpassword.setText("Password:");

        teacherpasswordtextbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacherpasswordtextboxActionPerformed(evt);
            }
        });

        TeacherLoginButton.setBackground(new java.awt.Color(0, 0, 51));
        TeacherLoginButton.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        TeacherLoginButton.setForeground(new java.awt.Color(255, 255, 255));
        TeacherLoginButton.setText("Login");
        TeacherLoginButton.setToolTipText("");
        TeacherLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeacherLoginButtonActionPerformed(evt);
            }
        });

        WrongPasswordLabel.setFont(new java.awt.Font("Calibri", 2, 14)); // NOI18N
        WrongPasswordLabel.setForeground(new java.awt.Color(229, 25, 42));

        javax.swing.GroupLayout TeacherLoginPanelLayout = new javax.swing.GroupLayout(TeacherLoginPanel);
        TeacherLoginPanel.setLayout(TeacherLoginPanelLayout);
        TeacherLoginPanelLayout.setHorizontalGroup(
            TeacherLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TeacherLoginPanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(TeacherLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(TeacherLoginPanelLayout.createSequentialGroup()
                        .addComponent(teacherid, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(teacheridtextbox, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(TeacherLoginPanelLayout.createSequentialGroup()
                        .addComponent(teacherpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(teacherpasswordtextbox, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(TeacherLoginPanelLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(TeacherLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TeacherLoginPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(TeacherLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TeacherLoginPanelLayout.createSequentialGroup()
                        .addComponent(teacherlogintitle, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TeacherLoginPanelLayout.createSequentialGroup()
                        .addComponent(WrongPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))))
        );
        TeacherLoginPanelLayout.setVerticalGroup(
            TeacherLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TeacherLoginPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(teacherlogintitle, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addGroup(TeacherLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teacheridtextbox, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teacherid, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(TeacherLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(teacherpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teacherpasswordtextbox, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addComponent(TeacherLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(WrongPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );

        StudentLoginPanel.setBackground(new java.awt.Color(255, 255, 255));

        StudentLoginTitle.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        StudentLoginTitle.setText("STUDENT LOGIN");
        StudentLoginTitle.setAlignmentY(0.0F);

        StudentId.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        StudentId.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        StudentId.setText("Exam ID:");

        StudentIdTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentIdTextBoxActionPerformed(evt);
            }
        });

        StudentPassword.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        StudentPassword.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        StudentPassword.setText("Password:");

        StudentPasswordTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentPasswordTextBoxActionPerformed(evt);
            }
        });

        StudentLoginButton.setBackground(new java.awt.Color(0, 0, 51));
        StudentLoginButton.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        StudentLoginButton.setForeground(new java.awt.Color(255, 255, 255));
        StudentLoginButton.setText("Login");
        StudentLoginButton.setToolTipText("");
        StudentLoginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                StudentLoginButtonMousePressed(evt);
            }
        });
        StudentLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentLoginButtonActionPerformed(evt);
            }
        });

        WrongPasswordLabel1.setFont(new java.awt.Font("Calibri", 2, 14)); // NOI18N
        WrongPasswordLabel1.setForeground(new java.awt.Color(0, 0, 51));

        javax.swing.GroupLayout StudentLoginPanelLayout = new javax.swing.GroupLayout(StudentLoginPanel);
        StudentLoginPanel.setLayout(StudentLoginPanelLayout);
        StudentLoginPanelLayout.setHorizontalGroup(
            StudentLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentLoginPanelLayout.createSequentialGroup()
                .addGroup(StudentLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StudentLoginPanelLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(StudentLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(StudentLoginPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(StudentLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(StudentLoginPanelLayout.createSequentialGroup()
                                .addComponent(StudentId, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(StudentIdTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(StudentLoginPanelLayout.createSequentialGroup()
                                .addComponent(StudentPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(StudentPasswordTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StudentLoginPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(StudentLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(StudentLoginTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WrongPasswordLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );
        StudentLoginPanelLayout.setVerticalGroup(
            StudentLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentLoginPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(StudentLoginTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94)
                .addGroup(StudentLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StudentLoginPanelLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(StudentId, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(StudentIdTextBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(StudentLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(StudentPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StudentPasswordTextBox))
                .addGap(58, 58, 58)
                .addComponent(StudentLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(WrongPasswordLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );

        LayeredPanel.setLayer(TeacherLoginPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        LayeredPanel.setLayer(StudentLoginPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout LayeredPanelLayout = new javax.swing.GroupLayout(LayeredPanel);
        LayeredPanel.setLayout(LayeredPanelLayout);
        LayeredPanelLayout.setHorizontalGroup(
            LayeredPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LayeredPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TeacherLoginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(LayeredPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(LayeredPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(StudentLoginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        LayeredPanelLayout.setVerticalGroup(
            LayeredPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LayeredPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TeacherLoginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(21, 21, 21))
            .addGroup(LayeredPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(LayeredPanelLayout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(StudentLoginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addComponent(TabPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LayeredPanel))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(LayeredPanel)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void teacherloginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teacherloginMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_teacherloginMousePressed

    private void TeacherLoginTabMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TeacherLoginTabMousePressed
        // TODO add your handling code here:
        TeacherLoginTab.setBackground(new Color(0,0,102));
        StudentLoginTab.setBackground(new Color(0,0,51));
        StudentLoginPanel.setVisible(false);
        TeacherLoginPanel.setVisible(true);
        
    }//GEN-LAST:event_TeacherLoginTabMousePressed

    private void teacheridtextboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacheridtextboxActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_teacheridtextboxActionPerformed

    private void StudentIdTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentIdTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StudentIdTextBoxActionPerformed

    private void StudentLoginTabMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StudentLoginTabMousePressed
        // TODO add your handling code here:
         TeacherLoginTab.setBackground(new Color(0,0,51));
         StudentLoginTab.setBackground(new Color(0,0,102));
        StudentLoginPanel.setVisible(true);
        TeacherLoginPanel.setVisible(false);
    }//GEN-LAST:event_StudentLoginTabMousePressed

    private void StudentLoginButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StudentLoginButtonMousePressed
        // TODO add your handling code here
         
    }//GEN-LAST:event_StudentLoginButtonMousePressed

    private void StudentPasswordTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentPasswordTextBoxActionPerformed
        // TODO add your handling code here:
         StudentPasswordTextBox.setText("");
    }//GEN-LAST:event_StudentPasswordTextBoxActionPerformed

    private void teacherpasswordtextboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherpasswordtextboxActionPerformed
        // TODO add your handling code here:
       teacherpasswordtextbox.setText(" ");
    }//GEN-LAST:event_teacherpasswordtextboxActionPerformed

    private void StudentLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentLoginButtonActionPerformed
        try {
            // TODO add your handling code here:
            StudentLoginMethod();
        } catch (IOException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_StudentLoginButtonActionPerformed

    private void TeacherLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeacherLoginButtonActionPerformed
        try {
            // TODO add your handling code here:
            TeacherLoginMethod();
        } catch (IOException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_TeacherLoginButtonActionPerformed

    private void studentloginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentloginMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentloginMousePressed

    public void StudentLoginMethod() throws IOException, ClassNotFoundException 
	{
             
                //WrongPasswordLabel1.setVisible(false);
		if(!StudentIdTextBox.getText().equals("") && !StudentPassword.getText().equals(""))
		{
			if(!StudentIdTextBox.getText().matches("-?\\d+(\\.\\d+)?"))
                        {
                            JOptionPane.showMessageDialog(this,"examId has numeric value!!","Error",JOptionPane.ERROR_MESSAGE);
                            this.dispose();
                            MainFrame obj=new MainFrame();
                            obj.setVisible(true);
                        } else
                        {
                        try 
			{
				dout.writeUTF("StudentLogin");
				int examId=Integer.parseInt(StudentIdTextBox.getText());
                                String studentPassword=StudentPasswordTextBox.getText();
                                
                                ClientServer student=new ClientServer(examId, studentPassword);
                                oout.writeObject(student);
                                StudentIdTextBox.setText("");
                                StudentPasswordTextBox.setText("");
                                 int flag=din.readInt();
                                if(flag==1)
                                {
                                     studentId=examId;
                                    StartTestFrame startTest=new StartTestFrame();
                                    startTest.setVisible(true);
                                    this.setVisible(false);
                                    dispose();
                                }
                                else
                                {
                                    JOptionPane.showMessageDialog(this,"Invalid examId or password","Error",JOptionPane.ERROR_MESSAGE);
                                    //WrongPasswordLabel1.setText("Invalid StudentId or Password");
                                    this.dispose();
                                    MainFrame obj=new MainFrame();
                                    obj.setVisible(true);
                                    //WrongPasswordLabel1.setVisible(true);
                                }
                        }
			catch(Exception e) 
			{
				e.printStackTrace();
                                //JOptionPane.showMessageDialog(this,"examId has numeric value!!","Error",JOptionPane.ERROR_MESSAGE);
			}
                        }
		}
                else
                    JOptionPane.showMessageDialog(this,"Fields cannot be empty!!","Error",JOptionPane.ERROR_MESSAGE);
		
		
	}
    
        public void TeacherLoginMethod() throws IOException 
	{
		if(!teacheridtextbox.getText().equals("") && !teacherpasswordtextbox.getText().equals(""))
		{
                        if(!teacheridtextbox.getText().matches("-?\\d+(\\.\\d+)?"))
                        {
                            JOptionPane.showMessageDialog(this,"teacherId has numeric value!!","Error",JOptionPane.ERROR_MESSAGE);
                            this.dispose();
                            MainFrame obj=new MainFrame();
                            obj.setVisible(true);
                        } else
                        {
			try 
			{
                               
				dout.writeUTF("TeacherLogin");
				int teacherId=Integer.parseInt(teacheridtextbox.getText());
                                String teacherPassword=teacherpasswordtextbox.getText();
                                
                                ClientServer teacher=new ClientServer(teacherId, teacherPassword);
                                oout.writeObject(teacher);
                                teacheridtextbox.setText("");
                                teacherpasswordtextbox.setText("");
                                int flag=din.readInt();
                                if(flag==1)
                                {
                                    TeacherPage teacherPage=new TeacherPage();
                                     teacherPage.setVisible(true);
                                    this.setVisible(false);
                                    dispose();
                                }
                                else
                                {
                                    JOptionPane.showMessageDialog(this,"Invalid teacherId or password","Error",JOptionPane.ERROR_MESSAGE);
                                    this.dispose();
                                    MainFrame obj=new MainFrame();
                                    obj.setVisible(true);
                                }
                        }
			catch(Exception e) 
			{
				//e.printStackTrace();
                            JOptionPane.showMessageDialog(this,"Teacher Id has numeric value!!","Error",JOptionPane.ERROR_MESSAGE);
			}
                        }
		}
                else
                    JOptionPane.showMessageDialog(this,"Fields cannot be empty!!","Error",JOptionPane.ERROR_MESSAGE);
		
		
	}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MainFrame().setVisible(true);
                    
                } catch (IOException ex) {
                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane LayeredPanel;
    private javax.swing.JLabel Login;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JLabel StudentId;
    private javax.swing.JTextField StudentIdTextBox;
    private javax.swing.JButton StudentLoginButton;
    private javax.swing.JPanel StudentLoginPanel;
    private javax.swing.JPanel StudentLoginTab;
    private javax.swing.JLabel StudentLoginTitle;
    private javax.swing.JLabel StudentPassword;
    private javax.swing.JPasswordField StudentPasswordTextBox;
    private javax.swing.JPanel TabPanel;
    private javax.swing.JButton TeacherLoginButton;
    private javax.swing.JPanel TeacherLoginPanel;
    private javax.swing.JPanel TeacherLoginTab;
    private javax.swing.JLabel WrongPasswordLabel;
    private javax.swing.JLabel WrongPasswordLabel1;
    private javax.swing.JLabel arrowicon;
    private javax.swing.JLabel arrowicon2;
    private javax.swing.JLabel icon;
    private javax.swing.JLabel icon1;
    private javax.swing.JLabel icon2;
    private javax.swing.JLabel studentlogin;
    private javax.swing.JLabel teacherid;
    private javax.swing.JTextField teacheridtextbox;
    private javax.swing.JLabel teacherlogin;
    private javax.swing.JLabel teacherlogintitle;
    private javax.swing.JLabel teacherpassword;
    private javax.swing.JPasswordField teacherpasswordtextbox;
    // End of variables declaration//GEN-END:variables
}
