




import ClientServer.ClientServer;
import java.awt.Color;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author admin
 */
public class StartTestFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    
    /*public static Socket cs=null;
    public static DataInputStream din=null;
    public static DataOutputStream dout=null;
    public static ObjectInputStream oin=null;
    public static ObjectOutputStream oout=null;*/
    
    
      ClientServer checkForSubjects;
    public StartTestFrame() throws IOException, ClassNotFoundException
    {
        initComponents();
         this.setTitle("Online Aptitude Test");
       
           MainFrame.dout.writeInt(MainFrame.studentId);
        checkForSubjects = (ClientServer) MainFrame.oin.readObject();
                int i=0;
                if(checkForSubjects.isSubject1==0)
                {//SubjectComboBox.addItem("Quantitative Aptitude");
                SubjectComboBox.insertItemAt("Quantitative Aptitude",i);
                i++;
                }
                if(checkForSubjects.isSubject2==0)
                {    //SubjectComboBox.addItem("Logical Reasoning");
                     SubjectComboBox.insertItemAt("Logical Reasoning", i);
                     i++;
                }
                if(checkForSubjects.isSubject3==0)
                {    //SubjectComboBox.addItem("Personality Aptitude");
                    SubjectComboBox.insertItemAt("Personality Aptitude", i);
                    i++;
                }
        InstructionsLabel.setText("<html>1. Total number of questions : 15.<br/>2. Time alloted : 15 minutes.<br/>3. Each question carry 2 marks, no negative marks.<br/>4. Click the “Submit Test” button given in bottom of the page to submit your test.<br/> 5. Test will be submitted automatically if the time expired.<br/>6. Don’t close the page.</html>");
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        UpperPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        SubjectLabel = new javax.swing.JLabel();
        SubjectComboBox = new javax.swing.JComboBox<>();
        InstructionsLabel = new javax.swing.JLabel();
        StartTestButton = new javax.swing.JButton();
        StartTestButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        MainPanel.setBackground(new java.awt.Color(255, 255, 255));

        UpperPanel.setBackground(new java.awt.Color(0, 0, 51));

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("INSTRUCTIONS");

        javax.swing.GroupLayout UpperPanelLayout = new javax.swing.GroupLayout(UpperPanel);
        UpperPanel.setLayout(UpperPanelLayout);
        UpperPanelLayout.setHorizontalGroup(
            UpperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpperPanelLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        UpperPanelLayout.setVerticalGroup(
            UpperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpperPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        SubjectLabel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        SubjectLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        SubjectLabel.setText("Choose Subject:");

        SubjectComboBox.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        SubjectComboBox.setToolTipText("Quantitative Aptitude\nLogical Reasoning\nPersonality Aptitude");
        SubjectComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubjectComboBoxActionPerformed(evt);
            }
        });

        InstructionsLabel.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        InstructionsLabel.setText("     Total number of questions : 20.     Time alloted : 30 minutes.     Each question carry 1 mark, no negative marks.     DO NOT refresh the page.     All the best :-).   ");

        StartTestButton.setBackground(new java.awt.Color(0, 0, 51));
        StartTestButton.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        StartTestButton.setForeground(new java.awt.Color(255, 255, 255));
        StartTestButton.setText("Start test");
        StartTestButton.setToolTipText("");
        StartTestButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                StartTestButtonMousePressed(evt);
            }
        });
        StartTestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartTestButtonActionPerformed(evt);
            }
        });

        StartTestButton1.setBackground(new java.awt.Color(0, 0, 51));
        StartTestButton1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        StartTestButton1.setForeground(new java.awt.Color(255, 255, 255));
        StartTestButton1.setText("Logout");
        StartTestButton1.setToolTipText("");
        StartTestButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                StartTestButton1MousePressed(evt);
            }
        });
        StartTestButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartTestButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(UpperPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(SubjectLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(SubjectComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106))
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(StartTestButton, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(236, 236, 236)
                .addComponent(StartTestButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(InstructionsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addComponent(UpperPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SubjectLabel)
                    .addComponent(SubjectComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(InstructionsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StartTestButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StartTestButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StartTestButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StartTestButtonMousePressed
        // TODO add your handling code here

    }//GEN-LAST:event_StartTestButtonMousePressed

    private void StartTestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartTestButtonActionPerformed
        System.out.println(checkForSubjects.isSubject1+" "+checkForSubjects.isSubject2+" "+checkForSubjects.isSubject3);
        if(checkForSubjects.isSubject1==1 && checkForSubjects.isSubject2==1 && checkForSubjects.isSubject3==1)
                JOptionPane.showMessageDialog(this,"No subject present.","Error",JOptionPane.ERROR_MESSAGE);
            else
        {
            try {                                                
            // TODO add your handling code here:
            
            
            int itemno=0;
            String selected_subject=(String) SubjectComboBox.getSelectedItem();
            /*if(SubjectComboBox.getSelectedItem()==null)
                 JOptionPane.showMessageDialog(this,"Select subject from given list.","Error",JOptionPane.ERROR_MESSAGE);
            else{*/
                MainFrame.dout.writeInt(MainFrame.studentId);
            
            try {
                /*ClientServer checkForSubjects=(ClientServer) MainFrame.oin.readObject();
                if(checkForSubjects.isSubject1==1)
                    SubjectComboBox.removeItemAt(0);
                else if(checkForSubjects.isSubject2==1)
                    SubjectComboBox.removeItemAt(1);
                else if(checkForSubjects.isSubject3==1)
                    SubjectComboBox.removeItemAt(2);
                */
                MainFrame.dout.writeUTF(selected_subject);
               // ClientServer checkForSubjects=(ClientServer) MainFrame.oin.readObject();
                
                if(selected_subject.equals("Quantitative Aptitude")==true || selected_subject.equals("Logical Reasoning"))
                {
                    QuestionFrame que_frame=new QuestionFrame();
                    que_frame.setVisible(true);
                    this.setVisible(false);
                    dispose();
                }
                else
                {
                    SubjectiveTestFrame sub_test=new SubjectiveTestFrame();
                    sub_test.setVisible(true);
                    this.setVisible(false);
                    dispose();
                }
                
            } catch (IOException ex) {
                Logger.getLogger(StartTestFrame.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(StartTestFrame.class.getName()).log(Level.SEVERE, null, ex);
            
            }    
        } catch (IOException ex) {
            Logger.getLogger(StartTestFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_StartTestButtonActionPerformed

    private void SubjectComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubjectComboBoxActionPerformed
        // TODO add your handling code here:
        if(SubjectComboBox.getSelectedItem().equals("Quantitative Aptitude") || SubjectComboBox.getSelectedItem().equals("Logical Reasoning"))
        InstructionsLabel.setText("<html>1. Total number of questions : 15.<br/>2. Time alloted : 15 minutes.<br/>3. Each question carry 2 marks, no negative marks.<br/>4. Click the “Submit Test” button given in bottom of the page to submit your test.<br/> 5. Test will be submitted automatically if the time expired.<br/>6. Don’t close the page.</html>");
        else
            InstructionsLabel.setText("<html>1. Total number of questions : 10.<br/>2. Time alloted : 20 minutes.<br/>3. Each question carry 4 marks, no negative marks.<br/>4. Click the “Submit Test” button given in bottom of the page to submit your test.<br/> 5. Test will be submitted automatically if the time expired.<br/>6. Don’t close the page.</html>");
    }//GEN-LAST:event_SubjectComboBoxActionPerformed

    private void StartTestButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StartTestButton1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_StartTestButton1MousePressed

    private void StartTestButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartTestButton1ActionPerformed
        // TODO add your handling code here:
        MainFrame start;
        
        try {
            start = new MainFrame();
            start.setVisible(true);
        setVisible(false);
        dispose();
        } catch (IOException ex) {
            Logger.getLogger(TeacherPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_StartTestButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                try {
                    //new StartTestFrame(StartTestFrame.cs, StartTestFrame.dout, StartTestFrame.oout, StartTestFrame.din, StartTestFrame.oin ).setVisible(true);
                    new StartTestFrame().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(StartTestFrame.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(StartTestFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel InstructionsLabel;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JButton StartTestButton;
    private javax.swing.JButton StartTestButton1;
    private javax.swing.JComboBox<String> SubjectComboBox;
    private javax.swing.JLabel SubjectLabel;
    private javax.swing.JPanel UpperPanel;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
